// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddFb-e-xH8PT3W_ig0aCUvAIIgB_i1Xg',
    appId: '1:103444921386:web:2499a5130254fba6051753',
    messagingSenderId: '103444921386',
    projectId: 'chatapp-6866b',
    authDomain: 'chatapp-6866b.firebaseapp.com',
    storageBucket: 'chatapp-6866b.appspot.com',
    measurementId: 'G-N0SEWH5495',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmGmfDG3Ja0vcWcIZZSBxe0z2CNWMuz7M',
    appId: '1:103444921386:android:5cc4c48673dcaf88051753',
    messagingSenderId: '103444921386',
    projectId: 'chatapp-6866b',
    storageBucket: 'chatapp-6866b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ozH4MLEcqK3sBj_87-zTjRdXXYEILJQ',
    appId: '1:103444921386:ios:a0162fb391ee9e98051753',
    messagingSenderId: '103444921386',
    projectId: 'chatapp-6866b',
    storageBucket: 'chatapp-6866b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ozH4MLEcqK3sBj_87-zTjRdXXYEILJQ',
    appId: '1:103444921386:ios:716481c2b7911865051753',
    messagingSenderId: '103444921386',
    projectId: 'chatapp-6866b',
    storageBucket: 'chatapp-6866b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
